export type Team = { id: string; name: string; flag: string };

export const TEAMS: Record<string, Team> = {
  MEX: { id: "MEX", name: "Mexico", flag: "🇲🇽" },
  RSA: { id: "RSA", name: "South Africa", flag: "🇿🇦" },
  KOR: { id: "KOR", name: "South Korea", flag: "🇰🇷" },
  CZE: { id: "CZE", name: "Czechia", flag: "🇨🇿" },
  CAN: { id: "CAN", name: "Canada", flag: "🇨🇦" },
  BIH: { id: "BIH", name: "Bosnia & Herz.", flag: "🇧🇦" },
  QAT: { id: "QAT", name: "Qatar", flag: "🇶🇦" },
  SUI: { id: "SUI", name: "Switzerland", flag: "🇨🇭" },
  BRA: { id: "BRA", name: "Brazil", flag: "🇧🇷" },
  MAR: { id: "MAR", name: "Morocco", flag: "🇲🇦" },
  HAI: { id: "HAI", name: "Haiti", flag: "🇭🇹" },
  SCO: { id: "SCO", name: "Scotland", flag: "🏴" },
  USA: { id: "USA", name: "United States", flag: "🇺🇸" },
  PAR: { id: "PAR", name: "Paraguay", flag: "🇵🇾" },
  AUS: { id: "AUS", name: "Australia", flag: "🇦🇺" },
  TUR: { id: "TUR", name: "Türkiye", flag: "🇹🇷" },
  GER: { id: "GER", name: "Germany", flag: "🇩🇪" },
  CUW: { id: "CUW", name: "Curaçao", flag: "🇨🇼" },
  CIV: { id: "CIV", name: "Ivory Coast", flag: "🇨🇮" },
  ECU: { id: "ECU", name: "Ecuador", flag: "🇪🇨" },
  NED: { id: "NED", name: "Netherlands", flag: "🇳🇱" },
  JPN: { id: "JPN", name: "Japan", flag: "🇯🇵" },
  SWE: { id: "SWE", name: "Sweden", flag: "🇸🇪" },
  TUN: { id: "TUN", name: "Tunisia", flag: "🇹🇳" },
  BEL: { id: "BEL", name: "Belgium", flag: "🇧🇪" },
  EGY: { id: "EGY", name: "Egypt", flag: "🇪🇬" },
  IRN: { id: "IRN", name: "Iran", flag: "🇮🇷" },
  NZL: { id: "NZL", name: "New Zealand", flag: "🇳🇿" },
  ESP: { id: "ESP", name: "Spain", flag: "🇪🇸" },
  CPV: { id: "CPV", name: "Cape Verde", flag: "🇨🇻" },
  KSA: { id: "KSA", name: "Saudi Arabia", flag: "🇸🇦" },
  URU: { id: "URU", name: "Uruguay", flag: "🇺🇾" },
  FRA: { id: "FRA", name: "France", flag: "🇫🇷" },
  SEN: { id: "SEN", name: "Senegal", flag: "🇸🇳" },
  IRQ: { id: "IRQ", name: "Iraq", flag: "🇮🇶" },
  NOR: { id: "NOR", name: "Norway", flag: "🇳🇴" },
  ARG: { id: "ARG", name: "Argentina", flag: "🇦🇷" },
  ALG: { id: "ALG", name: "Algeria", flag: "🇩🇿" },
  AUT: { id: "AUT", name: "Austria", flag: "🇦🇹" },
  JOR: { id: "JOR", name: "Jordan", flag: "🇯🇴" },
  POR: { id: "POR", name: "Portugal", flag: "🇵🇹" },
  COD: { id: "COD", name: "DR Congo", flag: "🇨🇩" },
  UZB: { id: "UZB", name: "Uzbekistan", flag: "🇺🇿" },
  COL: { id: "COL", name: "Colombia", flag: "🇨🇴" },
  ENG: { id: "ENG", name: "England", flag: "🏴" },
  CRO: { id: "CRO", name: "Croatia", flag: "🇭🇷" },
  GHA: { id: "GHA", name: "Ghana", flag: "🇬🇭" },
  PAN: { id: "PAN", name: "Panama", flag: "🇵🇦" },
};

export const GROUPS: { group: string; teams: string[] }[] = [
  { group: "A", teams: ["MEX", "RSA", "KOR", "CZE"] },
  { group: "B", teams: ["CAN", "BIH", "QAT", "SUI"] },
  { group: "C", teams: ["BRA", "MAR", "HAI", "SCO"] },
  { group: "D", teams: ["USA", "PAR", "AUS", "TUR"] },
  { group: "E", teams: ["GER", "CUW", "CIV", "ECU"] },
  { group: "F", teams: ["NED", "JPN", "SWE", "TUN"] },
  { group: "G", teams: ["BEL", "EGY", "IRN", "NZL"] },
  { group: "H", teams: ["ESP", "CPV", "KSA", "URU"] },
  { group: "I", teams: ["FRA", "SEN", "IRQ", "NOR"] },
  { group: "J", teams: ["ARG", "ALG", "AUT", "JOR"] },
  { group: "K", teams: ["POR", "COD", "UZB", "COL"] },
  { group: "L", teams: ["ENG", "CRO", "GHA", "PAN"] },
];

// Flat list of all 48 team IDs (group order) for the sticker marquee
export const ALL_TEAMS: string[] = GROUPS.flatMap((g) => g.teams);
